# 构建环境
main-build:
  stage: build
  image: node:18.20.4-alpine
  script:
    - *.npm-build
    - *.mp-wx-upload
  tags:
    - docker
  only:
    - main

main-notify:
  stage: notify
  <<: *email-notify
  variables:
    DOCKER_IMAGE_TAG: prod
  tags:
    - docker
  only:
    - main
